/**
 * unknown - Generated by Arbiter
 * Version: 1.0.0
 */

export function main(): void {
  console.log('Hello from unknown!');
}

// Auto-run if this file is executed directly
if (import.meta.url === `file://${process.argv[1]}`) {
  main();
}
