/**
 * Handlebars Template Renderer
 *
 * Provides Handlebars-based template rendering with custom helpers.
 * Used by the Plop implementor and can be used standalone.
 */

import Handlebars from "handlebars";

// Register custom helpers
registerHelpers();

// Register default partials
registerDefaultPartials();

function registerDefaultPartials(): void {
  // Default header partial - can be overridden by specific templates
  Handlebars.registerPartial("header", "// Generated by Arbiter\n");
}

function registerHelpers(): void {
  // Case transformations
  Handlebars.registerHelper("camelCase", (str: string) => {
    if (!str) return "";
    return str
      .replace(/[-_\s]+(.)?/g, (_, c) => (c ? c.toUpperCase() : ""))
      .replace(/^(.)/, (c) => c.toLowerCase());
  });

  Handlebars.registerHelper("pascalCase", (str: string) => {
    if (!str) return "";
    return str
      .replace(/[-_\s]+(.)?/g, (_, c) => (c ? c.toUpperCase() : ""))
      .replace(/^(.)/, (c) => c.toUpperCase());
  });

  Handlebars.registerHelper("snakeCase", (str: string) => {
    if (!str) return "";
    return str
      .replace(/([a-z])([A-Z])/g, "$1_$2")
      .replace(/[-\s]+/g, "_")
      .toLowerCase();
  });

  Handlebars.registerHelper("kebabCase", (str: string) => {
    if (!str) return "";
    return str
      .replace(/([a-z])([A-Z])/g, "$1-$2")
      .replace(/[_\s]+/g, "-")
      .toLowerCase();
  });

  Handlebars.registerHelper("upperCase", (str: string) => {
    return str?.toUpperCase() ?? "";
  });

  Handlebars.registerHelper("lowerCase", (str: string) => {
    return str?.toLowerCase() ?? "";
  });

  Handlebars.registerHelper("titleCase", (str: string) => {
    if (!str) return "";
    return str.replace(
      /\w\S*/g,
      (txt) => txt.charAt(0).toUpperCase() + txt.substr(1).toLowerCase(),
    );
  });

  // String utilities
  Handlebars.registerHelper("pluralize", (str: string) => {
    if (!str) return "";
    if (str.endsWith("y")) return str.slice(0, -1) + "ies";
    if (str.endsWith("s") || str.endsWith("x") || str.endsWith("ch") || str.endsWith("sh")) {
      return str + "es";
    }
    return str + "s";
  });

  Handlebars.registerHelper("singularize", (str: string) => {
    if (!str) return "";
    if (str.endsWith("ies")) return str.slice(0, -3) + "y";
    if (str.endsWith("es")) return str.slice(0, -2);
    if (str.endsWith("s")) return str.slice(0, -1);
    return str;
  });

  // Conditional helpers
  Handlebars.registerHelper("eq", (a: unknown, b: unknown) => a === b);
  Handlebars.registerHelper("ne", (a: unknown, b: unknown) => a !== b);
  Handlebars.registerHelper("lt", (a: number, b: number) => a < b);
  Handlebars.registerHelper("gt", (a: number, b: number) => a > b);
  Handlebars.registerHelper("lte", (a: number, b: number) => a <= b);
  Handlebars.registerHelper("gte", (a: number, b: number) => a >= b);
  Handlebars.registerHelper("and", (...args: unknown[]) => {
    // Remove the options object from args
    args.pop();
    return args.every(Boolean);
  });
  Handlebars.registerHelper("or", (...args: unknown[]) => {
    // Remove the options object from args
    args.pop();
    return args.some(Boolean);
  });
  Handlebars.registerHelper("not", (value: unknown) => !value);

  // Array/object helpers
  Handlebars.registerHelper("json", (obj: unknown, indent = 2) => {
    return JSON.stringify(obj, null, typeof indent === "number" ? indent : 2);
  });

  Handlebars.registerHelper("first", (arr: unknown[]) => {
    return Array.isArray(arr) ? arr[0] : undefined;
  });

  Handlebars.registerHelper("last", (arr: unknown[]) => {
    return Array.isArray(arr) ? arr[arr.length - 1] : undefined;
  });

  Handlebars.registerHelper("join", (arr: unknown[], separator = ", ") => {
    if (!Array.isArray(arr)) return "";
    return arr.join(typeof separator === "string" ? separator : ", ");
  });

  // Date helpers
  Handlebars.registerHelper("now", () => new Date().toISOString());
  Handlebars.registerHelper("year", () => new Date().getFullYear());

  // Path helpers
  Handlebars.registerHelper("basename", (str: string) => {
    if (!str) return "";
    return str.split("/").pop() ?? str;
  });

  Handlebars.registerHelper("dirname", (str: string) => {
    if (!str) return "";
    const parts = str.split("/");
    parts.pop();
    return parts.join("/") || ".";
  });

  // Default value helper
  Handlebars.registerHelper("default", (value: unknown, defaultValue: unknown) => {
    return value ?? defaultValue;
  });

  // Conditional block for checking if value exists and is not empty
  Handlebars.registerHelper(
    "ifPresent",
    function (this: unknown, value: unknown, options: Handlebars.HelperOptions) {
      if (value !== undefined && value !== null && value !== "") {
        if (Array.isArray(value) && value.length === 0) {
          return options.inverse(this);
        }
        return options.fn(this);
      }
      return options.inverse(this);
    },
  );
}

/**
 * Render a Handlebars template with context
 */
export function renderTemplate(template: string, context: Record<string, unknown>): string {
  const compiled = Handlebars.compile(template, { noEscape: true });
  return compiled(context);
}

/**
 * Compile a Handlebars template for repeated use
 */
export function compileTemplate(template: string): Handlebars.TemplateDelegate {
  return Handlebars.compile(template, { noEscape: true });
}

/**
 * Register a partial template
 */
export function registerPartial(name: string, template: string): void {
  Handlebars.registerPartial(name, template);
}

/**
 * Register a custom helper
 */
export function registerHelper(name: string, helper: Handlebars.HelperDelegate): void {
  Handlebars.registerHelper(name, helper);
}

export { Handlebars };
