// Shared Monaco CUE language configuration and tokenizer
export const CUE_LANGUAGE_CONFIG = {
  comments: {
    lineComment: "//",
    blockComment: ["/*", "*/"],
  },
  brackets: [
    ["{", "}"],
    ["[", "]"],
    ["(", ")"],
    ["<", ">"],
  ],
  autoClosingPairs: [
    { open: "{", close: "}" },
    { open: "[", close: "]" },
    { open: "(", close: ")" },
    { open: "<", close: ">" },
    { open: '"', close: '"', notIn: ["string"] },
    { open: "'", close: "'", notIn: ["string"] },
    { open: "`", close: "`", notIn: ["string"] },
  ],
  surroundingPairs: [
    { open: "{", close: "}" },
    { open: "[", close: "]" },
    { open: "(", close: ")" },
    { open: "<", close: ">" },
    { open: '"', close: '"' },
    { open: "'", close: "'" },
    { open: "`", close: "`" },
  ],
  folding: {
    markers: {
      start: new RegExp("^\\s*//\\s*#?region\\b"),
      end: new RegExp("^\\s*//\\s*#?endregion\\b"),
    },
  },
  wordPattern: /(-?\d*\.\d\w*)|([^`~!@#%^&*()\-=+\[\{}\|;:'",.<>/?\\s]+)/g,
  indentationRules: {
    increaseIndentPattern: /^((?!\/\/).)*(\{[^}"'`]*|\([^)"'`]*|\[[^\]"'`]*)$/,
    decreaseIndentPattern: /^((?!.*?\/\*).*\*)?\s*[)}\]]/,
  },
};

export const CUE_TOKENIZER = {
  defaultToken: "",
  keywords: ["package", "import", "if", "for", "in", "let", "true", "false", "null"],
  typeKeywords: ["string", "int", "float", "bool", "bytes", "number", "top", "bottom"],
  builtins: ["len", "close", "and", "or", "div", "mod", "quo", "rem", "list", "struct"],
  escapes: /\\(?:[abfnrtv\\"']|x[0-9A-Fa-f]{1,4}|u[0-9A-Fa-f]{4}|U[0-9A-Fa-f]{8})/,
  tokenizer: {
    root: [
      [/\/\/.*$/, "comment"],
      [/\/\*/, "comment", "@comment"],
      [/\b(?:if|for|in|let)\b/, "keyword.control"],
      [/\b(?:package|import)\b/, "keyword"],
      [/\b(?:string|int|float|bool|bytes|null|number|top|bottom|_)\b/, "type"],
      [/\b(?:true|false)\b/, "constant.language.boolean"],
      [/\bnull\b/, "constant.language.null"],
      [/\b(?:len|close|and|or|div|mod|quo|rem|list|struct)\b/, "support.function"],
      [/\d*\.\d+(?:[eE][\-+]?\d+)?/, "number.float"],
      [/0[xX][0-9a-fA-F]+/, "number.hex"],
      [/0[oO][0-7]+/, "number.octal"],
      [/0[bB][01]+/, "number.binary"],
      [/\d+/, "number"],
      [/"/, "string", "@string_double"],
      [/'/, "string", "@string_single"],
      [/`/, "string", "@string_backtick"],
      [/(?:\?=|\?:|\*=|=~|!~|!=|<=|>=|==)/, "keyword.operator.comparison"],
      [/(?:\.\.\.|\.\.<)/, "keyword.operator.range"],
      [/[&|](?![&|])/, "keyword.operator.unification"],
      [/!(?!=)/, "keyword.operator.logical"],
      [/@[a-zA-Z_]\w*/, "decorator"],
      [/_[a-zA-Z_]\w*/, "variable.other.constant"],
      [/#[a-zA-Z_$][\w$]*/, "variable.name"],
      [/\$[a-zA-Z_]\w*/, "variable.parameter"],
      [/\.[a-zA-Z_]\w*/, "variable.other.property"],
      [/[a-zA-Z_$][\w$]*/, "identifier"],
      [/[{}()\[\]]/, "@brackets"],
      [/[<>]/, "@brackets"],
      [/[=+\-*/%<>!&|^~?:,;.]/, "operator"],
      [/[ \t\r\n]+/, ""],
    ],
    comment: [
      [/[^/*]+/, "comment"],
      [/\*\//, "comment", "@pop"],
      [/[/*]/, "comment"],
    ],
    string_double: [
      [/[^\\"]+/, "string"],
      [/@escapes/, "string.escape"],
      [/\\./, "string.escape.invalid"],
      [/"/, "string", "@pop"],
    ],
    string_single: [
      [/[^\\']+/, "string"],
      [/@escapes/, "string.escape"],
      [/\\./, "string.escape.invalid"],
      [/'/, "string", "@pop"],
    ],
    string_backtick: [
      [/[^`]+/, "string"],
      [/`/, "string", "@pop"],
    ],
  },
};
