# Copy to wrangler.toml and fill in real values before deploying
name = "arbiter-claude-code"
main = "./worker.ts"
compatibility_date = "2024-04-05"
account_id = "<your-account-id>"

[vars]
ARBITER_HANDLER_IMAGE = "registry.example.com/arbiter-handlers/claude-code:latest"
ARBITER_HANDLER_ENDPOINT = "https://your-worker-subdomain.workers.dev/hooks/claude-code"
ARBITER_HANDLER_NAMESPACE = "claude-code"
ARBITER_HANDLER_OBJECT = "claude-code-webhook-container"
ARBITER_CONTAINER_FORWARD_ENV = "ARBITER_KV,ARBITER_BUCKET"

[[durable_objects.bindings]]
name = "CLAUDE_CODE_WEBHOOK_CONTAINER"
class_name = "ClaudeCodeWebhookContainer"

[[d1_databases]]
binding = "ARBITER_DB"
database_name = "arbiter"
database_id = "<d1-database-id>"

[[kv_namespaces]]
binding = "ARBITER_KV"
id = "<kv-namespace-id>"

[[r2_buckets]]
binding = "ARBITER_BUCKET"
bucket_name = "arbiter"

[[migrations]]
tag = "v1"
new_classes = ["ClaudeCodeWebhookContainer"]
