receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:
    timeout: 5s
    send_batch_size: 512
  attributes/r2:
    actions:
      - key: cloud.provider
        action: upsert
        value: cloudflare
      - key: cloud.region
        action: upsert
        value: ${env:R2_REGION}
      - key: r2.bucket
        action: upsert
        value: ${env:R2_BUCKET}
      - key: service.environment
        action: upsert
        value: ${env:OTEL_ENVIRONMENT:-cloudflare-workers}

exporters:
  awss3:
    s3uploader:
      region: ${env:R2_REGION}
      endpoint: ${env:R2_S3_ENDPOINT}
      s3_bucket: ${env:R2_BUCKET}
      s3_base_prefix: ${env:R2_BASE_PREFIX}
      s3_prefix: traces
      s3_partition_format: '%Y/%m/%d/%H/%M'
      s3_force_path_style: true
      compression: gzip
      file_prefix: otel-trace-
    marshaler: otlp_json
    encoding_file_extension: json.gz

extensions:
  health_check: {}
  pprof: {}
  zpages: {}

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [attributes/r2, batch]
      exporters: [awss3]
