apiVersion: v1
kind: Service
metadata:
  name: valhalla-arbiter
  namespace: valhalla
  labels:
    app.kubernetes.io/name: valhalla
    app.kubernetes.io/component: arbiter
    app.kubernetes.io/part-of: valhalla-agent-benchmarking
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
  selector:
    app.kubernetes.io/name: valhalla
    app.kubernetes.io/component: arbiter
---
apiVersion: v1
kind: Service
metadata:
  name: valhalla-mimir
  namespace: valhalla
  labels:
    app.kubernetes.io/name: valhalla
    app.kubernetes.io/component: mimir
    app.kubernetes.io/part-of: valhalla-agent-benchmarking
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP
    name: http
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
  selector:
    app.kubernetes.io/name: valhalla
    app.kubernetes.io/component: mimir
---
apiVersion: v1
kind: Service
metadata:
  name: valhalla-conclave
  namespace: valhalla
  labels:
    app.kubernetes.io/name: valhalla
    app.kubernetes.io/component: conclave
    app.kubernetes.io/part-of: valhalla-agent-benchmarking
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8082
    protocol: TCP
    name: http
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
  selector:
    app.kubernetes.io/name: valhalla
    app.kubernetes.io/component: conclave
---
apiVersion: v1
kind: Service
metadata:
  name: valhalla-metrics
  namespace: valhalla
  labels:
    app.kubernetes.io/name: valhalla
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: valhalla-agent-benchmarking
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
spec:
  type: ClusterIP
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
  selector:
    app.kubernetes.io/part-of: valhalla-agent-benchmarking