export const TYPE_ICON_STYLES: Record<string, string> = {
  service: "text-indigo-600 dark:text-indigo-200",
  api: "text-indigo-600 dark:text-indigo-200",
  worker: "text-purple-700 dark:text-purple-200",
  job: "text-amber-700 dark:text-amber-200",
  queue: "text-emerald-700 dark:text-emerald-200",
};

export const PATH_PRIORITY_CANDIDATES = [
  "packagePath",
  "package_path",
  "packageRoot",
  "package_root",
  "filePath",
  "file_path",
  "sourcePath",
  "source_path",
  "sourceDir",
  "source_dir",
  "source",
  "sourceDirectory",
  "source_directory",
  "path",
  "root",
  "rootPath",
  "root_path",
  "projectPath",
  "project_path",
  "workspacePath",
  "workspace_path",
  "repositoryPath",
  "repository_path",
  "directory",
  "entryPoint",
  "entrypoint",
  "modulePath",
  "module_path",
  "relativePath",
  "relative_path",
];
