analysis:
  enable_scoring: true
  enable_graph_analysis: true
  enable_lsh_analysis: false
  enable_refactoring_analysis: true
  enable_coverage_analysis: true
  enable_structure_analysis: true
  enable_names_analysis: true
  enable_cohesion_analysis: false
  confidence_threshold: 0.7
  max_files: 0
  exclude_patterns:
  - '*/node_modules/*'
  - '*/venv/*'
  - '*/target/*'
  - '*/__pycache__/*'
  - '*.min.js'
  - '*/__tests__/*'
  - '*.test.ts'
  - '*.spec.ts'
  include_patterns:
  - '**/*'
  ignore_patterns: []
  max_file_size_bytes: 512000
scoring:
  normalization_scheme: z_score
  use_bayesian_fallbacks: true
  confidence_reporting: false
  weights:
    complexity: 1.0
    graph: 0.8
    structure: 0.9
    style: 0.5
    coverage: 0.7
  statistical_params:
    confidence_level: 0.95
    min_sample_size: 10
    outlier_threshold: 3.0
graph:
  enable_betweenness: true
  enable_closeness: false
  enable_cycle_detection: true
  max_exact_size: 10000
  use_approximation: true
  approximation_sample_rate: 0.1
lsh:
  num_hashes: 128
  num_bands: 8
  shingle_size: 3
  similarity_threshold: 0.7
  max_candidates: 100
  use_semantic_similarity: false
  verify_with_apted: true
  apted_max_nodes: 4000
  apted_max_pairs_per_entity: 25
dedupe:
  include:
  - src/**
  exclude:
  - benchmarks/**
  - examples/**
  - datasets/**
  - '**/generated/**'
  - '**/*.pb.rs'
  min_function_tokens: 40
  min_ast_nodes: 20
  min_match_tokens: 24
  min_match_coverage: 0.4
  shingle_k: 9
  require_distinct_blocks: 2
  weights:
    ast: 0.35
    pdg: 0.45
    emb: 0.2
  io_mismatch_penalty: 0.25
  threshold_s: 0.82
  stop_phrases:
  - ^\s*@staticmethod\b
  - group\.bench_with_input\s*\(
  - \bb\.iter\s*\(\|\|
  - \bgroup\.finish\s*\(\)\s*;?
  - \blet\s+config\s*=\s*AnalysisConfig::(new|default)\s*\(\)\s*;?
  - \bchecks\.push\s*\(\s*HealthCheck\s*\{
  rank_by: saved_tokens
  min_saved_tokens: 100
  keep_top_per_file: 3
  adaptive:
    auto_denoise: true
    adaptive_learning: true
    rarity_weighting: true
    structural_validation: true
    live_reach_integration: true
    stop_motif_percentile: 0.75
    hub_suppression_threshold: 0.6
    quality_gate_percentage: 0.8
    tfidf_kgram_size: 8
    wl_iterations: 3
    min_rarity_gain: 1.2
    external_call_jaccard_threshold: 0.2
    cache_refresh_days: 7
    auto_refresh_cache: true
denoise:
  enabled: false
  auto: true
  min_function_tokens: 60
  min_match_tokens: 32
  require_blocks: 2
  similarity: 0.8
  weights:
    ast: 0.35
    pdg: 0.45
    emb: 0.2
  io_mismatch_penalty: 0.25
  threshold_s: 0.8
  stop_motifs:
    enabled: true
    percentile: 0.5
    refresh_days: 7
  auto_calibration:
    enabled: true
    quality_target: 0.8
    sample_size: 200
    max_iterations: 50
  ranking:
    by: saved_tokens
    min_saved_tokens: 100
    min_rarity_gain: 1.2
    live_reach_boost: true
  dry_run: false
languages:
  javascript:
    enabled: true
    file_extensions:
    - .js
    - .mjs
    - .jsx
    tree_sitter_language: javascript
    max_file_size_mb: 5.0
    complexity_threshold: 10.0
    additional_settings: {}
  rust:
    enabled: true
    file_extensions:
    - .rs
    tree_sitter_language: rust
    max_file_size_mb: 10.0
    complexity_threshold: 15.0
    additional_settings: {}
  go:
    enabled: true
    file_extensions:
    - .go
    tree_sitter_language: go
    max_file_size_mb: 8.0
    complexity_threshold: 12.0
    additional_settings: {}
  python:
    enabled: true
    file_extensions:
    - .py
    - .pyi
    tree_sitter_language: python
    max_file_size_mb: 10.0
    complexity_threshold: 10.0
    additional_settings: {}
  typescript:
    enabled: true
    file_extensions:
    - .ts
    - .tsx
    - .d.ts
    tree_sitter_language: typescript
    max_file_size_mb: 5.0
    complexity_threshold: 10.0
    additional_settings: {}
io:
  cache_dir: null
  enable_caching: true
  cache_ttl_seconds: 3600
  report_dir: null
  report_format: json
performance:
  max_threads: null
  memory_limit_mb: null
  file_timeout_seconds: 30
  total_timeout_seconds: null
  enable_simd: true
  batch_size: 100
structure:
  enable_branch_packs: true
  enable_file_split_packs: true
  top_packs: 20
  fsdir:
    max_files_per_dir: 25
    max_subdirs_per_dir: 10
    max_dir_loc: 2000
    min_branch_recommendation_gain: 0.15
    min_files_for_split: 5
    target_loc_per_subdir: 1000
    optimal_files: 7
    optimal_files_stddev: 2.0
    optimal_subdirs: 3
    optimal_subdirs_stddev: 1.5
  fsfile:
    huge_loc: 800
    huge_bytes: 128000
    min_split_loc: 200
    min_entities_per_split: 3
    optimal_ast_nodes: 2000
    ast_nodes_95th_percentile: 6000
  partitioning:
    balance_tolerance: 0.25
    max_clusters: 4
    min_clusters: 2
    naming_fallbacks:
    - core
    - io
    - api
    - util
  entity_health:
    function_size:
      optimal: 200
      percentile_95: 800
      penalty_center: 0.9
      penalty_steepness: 0.05
    class_size:
      optimal: 500
      percentile_95: 3000
      penalty_center: 0.9
      penalty_steepness: 0.05
    file_size:
      optimal: 2000
      percentile_95: 6000
      penalty_center: 0.9
      penalty_steepness: 0.05
  exclude_patterns: []
coverage:
  auto_discover: true
  search_paths:
  - ./coverage/
  - ./target/coverage/
  - ./target/tarpaulin/
  - ./target/
  - ./.coverage/
  - ./htmlcov/
  - ./coverage-reports/
  - ./reports/
  - ./test-results/
  - ./build/coverage/
  - ./build/test-results/
  - ./
  file_patterns:
  - coverage.xml
  - lcov.info
  - coverage.json
  - coverage.lcov
  - cobertura.xml
  - coverage-final.json
  - coverage-summary.json
  - .coverage
  - junit.xml
  - jacoco.xml
  - clover.xml
  - '**/coverage.xml'
  - '**/lcov.info'
  - '**/coverage.json'
  - '**/cobertura.xml'
  - '**/jacoco.xml'
  - '**/clover.xml'
  - target/coverage/*.xml
  - target/tarpaulin/coverage.xml
  - target/llvm-cov/coverage.lcov
  - build/coverage/*.xml
  - coverage/coverage-final.json
  - htmlcov/coverage.json
  - '**/build/jacoco/*.xml'
  - '**/build/reports/jacoco/test/*.xml'
  - '**/build/test-results/test/*.xml'
  max_age_days: 7
  coverage_file: null
  enabled: false
  report_paths:
  - coverage.xml
  - lcov.info
  - coverage-final.json
  max_gaps_per_file: 5
  min_gap_loc: 3
  snippet_context_lines: 5
  long_gap_head_tail: 2
  group_cross_file: false
  target_repo_gain: 0.02
  weights:
    size: 0.4
    complexity: 0.2
    fan_in: 0.15
    exports: 0.1
    centrality: 0.1
    docs: 0.05
  exclude_patterns:
  - '**/tests/**'
  - '**/spec/**'
docs:
  min_fn_nodes: 5
  min_file_nodes: 50
  min_files_per_dir: 5
cohesion:
  enabled: false
  embedding:
    model: EmbeddingGemma300M
    cache_dir: null
    show_download_progress: false
    batch_size: 32
    dimension: 768
  symbols:
    tfidf_mass_threshold: 0.8
    min_symbols: 5
    max_symbols: 40
    sublinear_coefficient: 3.0
    include_signature: true
    include_doc_summary: false
    max_doc_summary_tokens: 20
  thresholds:
    min_cohesion: 0.3
    min_doc_alignment: 0.4
    min_doc_specificity: 0.3
    min_doc_tokens: 6
    min_outlier_similarity: 0.2
    outlier_percentile: 0.1
    use_percentile_thresholds: true
  rollup:
    min_file_entities: 5
    min_folder_files: 2
    file_weight_function: Log
    centroid_trim_percent: 0.15
    use_mad_trimming: false
    mad_multiplier: 1.5
  issues:
    max_issues_per_category: 50
    skip_generated_paths: true
    exclude_patterns:
    - '**/node_modules/**'
    - '**/vendor/**'
    - '**/build/**'
    - '**/dist/**'
    - '**/target/**'
    - '**/.git/**'
    - '**/generated/**'
    - '**/*.generated.*'
    - '**/*.min.js'
    - '**/*.bundle.js'
    include_patterns: []
